### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by jpmurray** [spatie/vue-form-backend-validation#1]
I've been through the Laracasts' videos last week, and I really liked the work, so thanks for packaging this.

Quick question though, as I don't see this in the usage section: _where_ exactly would you require the package exactly? My initial thought was that you'd probably make a reusable component out of this, but it seems like you didn't, and Jeffrey used the classes he made directly in a "master" js file.

So, say in a more traditional Laravel project, how do you envision this being used?

Would you`require` this package in `app.js` or `bootstrap.js`? Would you use the code in all of your `component.vue` files?  Something else?

**Comment by freekmurze** [comment]
Hi,

you're a quick one 😄 

This package is currently in development, the API isn't stable yet, documentation still has to be written.

So have a little more patience while we finish up our work. Prudent ETA: mid January 2017.

**Comment by freekmurze** [comment]
I've added a little not in the `readme` explaining that this package isn't finished yet.

**Comment by jpmurray** [comment]
HAHA, yeah, I follow you and I was kind of currently playing with Jeffrey's class at the time I was that you created the repo! 🤣
